### ISSUE TITLE
Un-fdroid version

### ISSUE THREAD

**Issue by BabyOilJohnson** [aleksey-saenko/MusicRecognizer#26]
Can u release a dev signed version of the app?

**Comment by BabyOilJohnson** [comment]
I have trust issue with fdroid that's why 😅.

**Comment by aleksey-saenko** [comment]
It seems that F-Droid deserves more trust than a random developer on GitHub (me). F-Droid builds the application from a snapshot of the source code, and anyone can check what is in the code. If I build a personal obfuscated build, you will have to trust me that I built the application from the code of this repository and didn't add anything extra.
Why is there such distrust of F-Droid? Did I miss something about it?

**Comment by BabyOilJohnson** [comment]
I think I can trust u than a third party(fdroid).

> Why is there such distrust of F-Droid? Did I miss something about it?

Read this [article](https://privsec.dev/posts/android/f-droid-security-issues/)

Becuz of this I mainly use [Obtainium](https://github.com/ImranR98/Obtainium).

**Comment by aleksey-saenko** [comment]
Thanks for the article. In general, there are good arguments (not to stop using F-Droid, but at least to offer an alternative). I didn't really want to publish another version of the application since it would not be compatible with the previously published one. This may be confusing to some users. But it seems like I will have to. I'll think about what can be done.

**Comment by BabyOilJohnson** [comment]
Thanks a lot 🙏

Closing this issue, as it got resolved.

**Comment by bt4ibwem8** [comment]
@aleksey-saenko 
Why just don't make reproducible build (signed by you) in f-droid?

**Comment by aleksey-saenko** [comment]
@bt4ibwem8 
As I understand it, achieving reproducible builds is not a straightforward process and there may be strange situations where reproduction is violated. It involves delving into the problem, spending time on solving it, which seems like an additional headache with little noticeable impact since not many users are aware of or concerned about it. Potentially, it could be done, but currently there are no plans.
