### ISSUE TITLE
Show recognized song lyrics

### ISSUE THREAD

**Issue by GuiSousa135** [aleksey-saenko/MusicRecognizer#33]
When recognizing a song, save and show the full lyrics of the song below the links, just like in the Audire project (https://github.com/alexmercerind/audire)

![284404669-050994eb-11d3-4e1d-bb4b-53eea33855e9](https://github.com/aleksey-saenko/MusicRecognizer/assets/55188286/e2a0dbea-c811-4fde-8def-1cfbf919bf61)

**Comment by aleksey-saenko** [comment]
For now, if the lyrics of a song have been found, you can easily access them with just one click on the lyrics icon in the top bar. The lyrics of the song aren't the primary information about the track, and not everyone requires them during the recognition process. That's why they aren't displayed on the track screen to prevent cluttering the interface. While I don't think the current interface is perfect, I also don't believe this suggestion is the right fit.

**Comment by aleksey-saenko** [comment]
If you have any further suggestions, you can share them in this [discussion](https://github.com/aleksey-saenko/MusicRecognizer/discussions/34).
