### ISSUE TITLE
Link to Cifra Club

### ISSUE THREAD

**Issue by GuiSousa135** [aleksey-saenko/MusicRecognizer#38]
Add a button that redirects to the song in the Cifra Club app or website (cifraclub.com), used by instrumentalists and musicians

**Comment by aleksey-saenko** [comment]
Hello!
Unfortunately, this site is not a mainstream audio streaming platform and is not supported by the services currently used in the application (AudD and Odesli).
While it is possible to create a button that redirects to a search for this site, it does not seem justified since the application doesn't aim to show a search button for every music-related site. This would result in endless growth and make maintenance very difficult.
Instead, I suggest copying the track name by long-pressing on the title, then switching to the desired application and pasting it into the search.
