### ISSUE TITLE
Feature request: Force retry for saved recognitions

### ISSUE THREAD

**Issue by nutpantz** [aleksey-saenko/MusicRecognizer#9]
I have 4 recordings that are not recognized in the que when i forgot to enable wifi.the songs are not recognized after i turned wifi on.
And i know the songs are recognizable because i tested them in "live"mode

I push start and it seems to do nothing but charge the icon

**Comment by aleksey-saenko** [comment]
@nutpantz 
For each scheduled recognition, a special worker is created, and its launch is controlled by the Android system. Even if the internet connection becomes available, there might be a delay in starting the worker due to the implementation of an exponential backoff policy. I have some control over this delay, but it doesn't seem to be a significant issue. Please let me know if you disagree or if the worker fails to start even after a certain period of time.
Regarding the "start icon". Do you want to say that pressing the play button doesn't produce the sound of recording (please check device volume)?

**Comment by nutpantz** [comment]
Yes there needs to be a manual force retry recognition option.
The Android system is not fantastic for starting things based on if it thinks you have a good internet connection or not.

**Comment by aleksey-saenko** [comment]
Version 1.1.3 released on F-Droid with force retry recognition option.
